// Exercice 2
// https://projecteuler.net/problem=2

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

let pastResult = 1;
let result = 2;
let newResult = 3;
let sum = 2;

while (newResult < 4000000) {
    newResult = pastResult + result
    if (newResult % 2 == 0) {
        console.log(newResult)
        sum += newResult;
    } 
    pastResult = result;
    result = newResult;
}
console.log(sum);
