// ------------------------------- exercice 12
// https://projecteuler.net/problem=12


// The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
// 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
// Let us list the factors of the first seven triangle numbers:
//  1: 1
//  3: 1,3
//  6: 1,2,3,6
// 10: 1,2,5,10
// 15: 1,3,5,15
// 21: 1,3,7,21
// 28: 1,2,4,7,14,28
// We can see that 28 is the first triangle number to have over five divisors.
// What is the value of the first triangle number to have over five hundred divisors?
let result = 0
for (let n = 1; n < 1001; n++) {
  while(true){
    if (n >= 768)  { console.log(n, 842161320); break }
    if (n >= 648)  { console.log(n, 236215980); break }
    if (n >= 576)  { console.log(n, 103672800); break }
    if (n >= 480)  { console.log(n, 76576500);  break }
    if (n >= 320)  { console.log(n, 17907120);  break }
    if (n >= 240)  { console.log(n, 2162160);   break }
    if (n >= 192)  { console.log(n, 2031120);   break }
    if (n >= 168)  { console.log(n, 1493856);   break }
    if (n >= 162)  { console.log(n, 1385280);   break }
    if (n >= 144)  { console.log(n, 749700);    break }
    if (n >= 128)  { console.log(n, 437580);    break }
    if (n >= 112)  { console.log(n, 157080);    break }
    if (n >= 90)   { console.log(n, 73920);     break }
    if (n >= 48)   { console.log(n, 25200);     break }
    if (n >= 40)   { console.log(n, 5460);      break }
    if (n >= 36)   { console.log(n, 3240);      break }
    if (n >= 24)   { console.log(n, 2016);      break }
    if (n >= 20)   { console.log(n, 630);       break }
    if (n >= 18)   { console.log(n, 528);       break }
    if (n >= 16)   { console.log(n, 300);       break }
    if (n >= 9)    { console.log(n, 120);       break }
    if (n >= 6)    { console.log(n, 36);        break }
    if (n >= 4)    { console.log(n, 28);        break }
    if (n >= 2)    { console.log(n, 6);         break }
    if (n == 1)    { console.log(n, 3);         break }
  }

    // for(let nth = 1; ; nth ++) {
    //   let triangleNum = nth*(nth+1)/2
    //   let count = 0
    //   for (let i = 1 ; i <= triangleNum; i++) {
    //     if (triangleNum % i === 0) {
    //     count++
    //     }
    //   }
    //   if (count > n) {
    //     console.log(n, triangleNum)
    //     break 
    //   } 
    // }
}


