// ------------------------------- exercice 12
// https://projecteuler.net/problem=12


// The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
// 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
// Let us list the factors of the first seven triangle numbers:
//  1: 1
//  3: 1,3
//  6: 1,2,3,6
// 10: 1,2,5,10
// 15: 1,3,5,15
// 21: 1,3,7,21
// 28: 1,2,4,7,14,28
// We can see that 28 is the first triangle number to have over five divisors.
// What is the value of the first triangle number to have over five hundred divisors?


let divCount = 0;
let row = 0;
let colNum = 0;
let sumTriangle = 0;
let reminder = 0;
let maxcount = 0;


for (let i = 0; divCount == 16; i++) {
    divCount = 0;
    colNum += 1;
    row += 1;
    sumTriangle += colNum;
    for (let j = 1; j <= sumTriangle; j++) {
        if (sumTriangle % j == 0) {
            divCount += 1;
        }

    }
    if (divCount > maxcount) {
        maxcount = divCount;
        console.log(maxcount);
        console.log(" ");
        console.log("for a total of " + divCount + " possible divisions");
        console.log(" ");
        console.log(" ");
        console.log(" ");
        console.log(sumTriangle);

    }

}
